In [4]:
import duckdb                             

conn = duckdb.connect("business.db")

In [6]:
conn.execute("""
CREATE OR REPLACE TABLE customers(
    customer_id INTEGER,
    customer_name VARCHAR,
    city VARCHAR
);
""")

conn.execute("""
INSERT INTO customers VALUES
(1,'Krish','Mumbai'),
(2,'Rahul','Pune'),
(3,'Aman','Delhi'),
(4,'Priya','Mumbai'),
(5,'Neha','Bangalore');
""")

In [7]:
conn.execute("""
CREATE OR REPLACE TABLE products(
    product_id INTEGER,
    product_name VARCHAR,
    category VARCHAR,
    price DOUBLE
);
""")

conn.execute("""
INSERT INTO products VALUES
(1,'Laptop','Electronics',60000),
(2,'Phone','Electronics',30000),
(3,'Mouse','Accessories',1000),
(4,'Keyboard','Accessories',2000),
(5,'Monitor','Electronics',15000);
""")

In [8]:
conn.execute("""
CREATE OR REPLACE TABLE orders(
    order_id INTEGER,
    customer_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    order_date DATE
);
""")

conn.execute("""
INSERT INTO orders VALUES
(101,1,1,1,'2025-01-01'),
(102,2,2,2,'2025-01-02'),
(103,1,3,5,'2025-01-03'),
(104,3,1,1,'2025-01-04'),
(105,4,5,2,'2025-01-05'),
(106,5,2,1,'2025-01-06');
""")

select

In [9]:
conn.sql("""
SELECT *
FROM customers;
""").df()

   customer_id customer_name       city
0            1         Krish     Mumbai
1            2         Rahul       Pune
2            3          Aman      Delhi
3            4         Priya     Mumbai
4            5          Neha  Bangalore

where

In [10]:
conn.sql("""
SELECT *
FROM customers
WHERE city='Mumbai';
""").df()

   customer_id customer_name    city
0            1         Krish  Mumbai
1            4         Priya  Mumbai

Group by

In [11]:
conn.sql("""
SELECT
city,
COUNT(*) AS total_customers
FROM customers
GROUP BY city;
""").df()

        city  total_customers
0  Bangalore                1
1      Delhi                1
2     Mumbai                2
3       Pune                1

having

In [12]:
conn.sql("""
SELECT
city,
COUNT(*) AS total_customers
FROM customers
GROUP BY city
HAVING COUNT(*) > 1;
""").df()

     city  total_customers
0  Mumbai                2

join

In [13]:
conn.sql("""
SELECT
c.customer_name,
o.order_id
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id;
""").df()

  customer_name  order_id
0         Krish       103
1         Rahul       102
2          Aman       104
3         Priya       105
4          Neha       106
5         Krish       101

subquery

In [14]:
conn.sql("""
SELECT *
FROM products
WHERE price >
(
SELECT AVG(price)
FROM products
);
""").df()

   product_id product_name     category    price
0           1       Laptop  Electronics  60000.0
1           2        Phone  Electronics  30000.0

window function

In [15]:
conn.sql("""
SELECT
product_name,
price,
RANK() OVER(
ORDER BY price DESC
) AS rank_num
FROM products;
""").df()

  product_name    price  rank_num
0       Laptop  60000.0         1
1        Phone  30000.0         2
2      Monitor  15000.0         3
3     Keyboard   2000.0         4
4        Mouse   1000.0         5

In [ ]:
SELECT COUNT(*) AS total_customers
FROM customers;