In [1]:
import numpy as np
import pandas as pd

In [3]:
sales = pd.read_csv("sales.csv")

In [8]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       30 non-null     int64
 1   Order Date     30 non-null     str
 2   Customer ID    30 non-null     str
 3   Customer Name  30 non-null     str
 4   Product        30 non-null     str
 5   Category       30 non-null     str
 6   Sub-Category   30 non-null     str
 7   Region         30 non-null     str
 8   City           30 non-null     str
 9   Sales          30 non-null     int64
 10  Quantity       30 non-null     int64
 11  Discount       30 non-null     float64
 12  Profit         30 non-null     int64
dtypes: float64(1), int64(4), str(8)
memory usage: 3.2 KB

In [7]:
sales.describe()

          Order ID        Sales   Quantity   Discount      Profit
count    30.000000    30.000000  30.000000  30.000000   30.000000
mean   1015.500000   514.666667   4.233333   0.075000  110.666667
std       8.803408   404.442855   5.096878   0.063991   90.535317
min    1001.000000    25.000000   1.000000   0.000000    8.000000
25%    1008.250000    82.500000   1.000000   0.012500   32.500000
50%    1015.500000   500.000000   2.000000   0.050000   90.000000
75%    1022.750000   787.500000   4.750000   0.100000  150.000000
max    1030.000000  1400.000000  20.000000   0.200000  320.000000

1 total revenue

In [4]:
sales["Sales"].sum()

np.int64(15440)

2 total profit

In [9]:
sales["Profit"].sum()

np.int64(3320)

3 average value

In [10]:
sales["Sales"].mean()

np.float64(514.6666666666666)

4 top 10 products

In [11]:
sales.groupby("Product")["Sales"] \
.sum() \
.sort_values(ascending=False) \
.head(10)

Product
Laptop          3850
Monitor         2550
Desk            1950
Sofa            1850
Tablet          1450
Office Chair    1170
Bookshelf       1050
Printer          950
Keyboard         270
Notebook         175
Name: Sales, dtype: int64

5 revenue by region

In [12]:
sales.groupby("Region")["Sales"].sum()

Region
Central    1330
East       6590
South      2580
West       4940
Name: Sales, dtype: int64

6 Profit by region

In [13]:
sales.groupby("Region")["Profit"].sum()

Region
Central     265
East       1485
South       465
West       1105
Name: Profit, dtype: int64

7 best category

In [14]:
sales.groupby("Category")["Sales"] \
.sum() \
.sort_values(ascending=False)

Category
Technology         9155
Furniture          6020
Office Supplies     265
Name: Sales, dtype: int64

8 best sub - category

In [15]:
sales.groupby("Sub-Category")["Sales"] \
.sum() \
.sort_values(ascending=False)

Sub-Category
Laptops        3850
Monitors       2550
Tables         1950
Furnishings    1850
Tablets        1450
Chairs         1170
Bookcases      1050
Printers        950
Accessories     355
Paper           175
Binders          65
Storage          25
Name: Sales, dtype: int64

9 higest selling customer

In [16]:
sales.groupby("Customer Name")["Sales"] \
.sum() \
.sort_values(ascending=False) \
.head()

Customer Name
Alice Johnson    2450
Nina King        1950
Lisa Hall        1650
Rachel Evans     1300
Charlie Brown    1150
Name: Sales, dtype: int64

10 average discount

In [17]:
sales["Discount"].mean()

np.float64(0.075)

11 most orderd product

In [18]:
sales["Product"].value_counts().head()

Product
Laptop          3
Office Chair    3
Desk            3
Notebook        3
Monitor         3
Name: count, dtype: int64

12 higest profit product

In [19]:
sales.groupby("Product")["Profit"] \
.sum() \
.sort_values(ascending=False) \
.head()

Product
Laptop     930
Monitor    600
Desk       410
Tablet     320
Sofa       250
Name: Profit, dtype: int64

13 top 5 cities

In [22]:
sales.groupby("City")["Sales"] \
.sum() \
.sort_values(ascending=False) \
.head()

City
New York        3340
Seattle         2900
Boston          1700
Philadelphia    1550
Los Angeles     1170
Name: Sales, dtype: int64

14 region wise statistics

In [23]:
sales.groupby("Region").agg({
    "Sales":["sum","mean","max"],
    "Profit":["sum","mean"],
    "Discount":"mean"
})

        Sales                   Profit              Discount
          sum        mean   max    sum        mean      mean
Region
Central  1330  221.666667   600    265   44.166667  0.058333
East     6590  732.222222  1250   1485  165.000000  0.072222
South    2580  368.571429   900    465   66.428571  0.085714
West     4940  617.500000  1400   1105  138.125000  0.081250